### ISSUE TITLE
Could not find a matching version of package spatie/ray-bundle.

### ISSUE THREAD

**Issue by sietseveenman** [spatie/ray-bundle#1]
Running into this [InvalidArgumentException]  when  trying to run 'composer require spatie/ray-bundle'

Could not find a matching version of package spatie/ray-bundle. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable). 

Symfony 5.1
PHP 7.4

**Comment by Nielsvanpach** [comment]
This package has not been released yet. We could use a bit of help with a Symfony package for Ray, so feel free to submit a PR!

For now you can use [spatie/ray](https://github.com/spatie/ray) in your Symfony projects.
