### ISSUE TITLE
Symfony 6/7 support

### ISSUE THREAD

**Issue by gander** [spatie/ray-bundle#2]
https://github.com/spatie/ray-bundle/discussions/new?category=ideas => 404

Symfony 7 was released today and this package is only compatible with 5 at most. It's time to do something about it.

**Comment by freekmurze** [comment]
Hi, we'd accept a PR that fixes this! 👍

**Comment by gander** [comment]
Prima Aprilis, huh?

**Comment by gander** [comment]
I will do this PR when the [tests](https://github.com/spatie/ray-bundle/issues/3) start working.

**Comment by Nielsvanpach** [comment]
This package was never released on Packagist

**Comment by gander** [comment]
So, did this package only exist to trick Symfony users into thinking it's supported by Symfony and get them to buy the software? But it's a bit strange because how else would I install it and find out it doesn't work? It's weird. I must have installed it through Packagist two years ago. How else would I install it and discover it doesn't work?

**Comment by gander** [comment]
If you don't plan to "publish" it, why do you keep it in this form? This looks like a scam to me, suggesting that Ray has a bundle for Symfony.

**Comment by Nielsvanpach** [comment]
This package was never released or published to Packagist. I assume you have installed [spatie/ray](https://github.com/spatie/ray) previously.

To clarify, there hasn't been any communication regarding a specific Ray bundle on our end. You can use spatie/ray.

For information, I encourage you to read the docs: https://myray.app/docs
